site_name: python-platonic

nav:
  - Structures:
      - Introduction: structures/index.md
      - Queue: structures/queue/index.md
  - Amazon SQS:
      - SQS Queue: sqs/queue.md
  - Extra:
      - Typecasts: typecasts.md
      - DDD: ddd.md

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
