site_name: python-platonic
repo_url: https://github.com/python-platonic/
repo_name: python-platonic
edit_uri: website/edit/master/platonic.tools/docs/
copyright: Copyright &copy; 2021 python-platonic

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true
  - mkautodoc
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
      # make exceptions to highlighting of code:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:mermaid2.fence_mermaid

plugins:
  - search
  - octadocs
  - macros:
      modules:
        - octadocs.macros
#  - mermaid2

theme:
  name: material
  logo: assets/platonic.png
  favicon: assets/platonic-favicon.png
  custom_dir: overrides
  palette:
    primary: teal
    scheme: slate
  features:
    - navigation.tabs
    - header.autohide

extra_css:
  - css/custom.css

extra:
  # Dummy SQS queue URL for demonstration purposes
  sqs_queue_url: https://sqs.us-west-2.amazonaws.com/123456789012/queue-name
