# https://github.com/netlify/build-image/issues/221

[build]
publish = "site/"
command = """
pip install -q poetry &&
poetry config settings.virtualenvs.in-project true &&
poetry install &&
poetry run mkdocs build
"""
